modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="projectforge"
version="1.0.0"
displayName="Project Forge"
description="Basic Forge mod template"
authors="exemple"

[[dependencies.projectforge]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.projectforge]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"